name: tagpr
on:
  push:
    branches:
    - "master"
  workflow_dispatch:
jobs:
  tagpr:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
      issues: read
      pull-requests: write
    steps:
    - name: checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: setup go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version-file: go.mod
    - name: tagpr
      id: tagpr
      uses: Songmu/tagpr@84850af451fc53753c6685a3a6a2af7beef23607 # v1.18.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: ./.github/actions/release
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.tagpr.outputs.tag }}
      if: "steps.tagpr.outputs.tag != ''"
